import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.scss";

import { ReactNode } from "react";
import NavBar from "@/components/navigation/NavBar";
import styles from "./layout.module.css";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.className}>
        <body>
            <NavBar />
            <div className={styles.page}>
                {children}
            </div>
        </body>
    </html>
  );
}
