import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.scss";

import { ReactNode } from "react";
import NavBar from "@/components/navigation/NavBar";
import styles from "./layout.module.css";

import { NextIntlClientProvider, hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";

const outfit = Outfit({
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                             params,
                                         }: {
    children: ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;

    if (!hasLocale(routing.locales, locale)) {
    }

    return (
        <html lang={locale} className={outfit.className}>
            <body>
                <NextIntlClientProvider locale={locale}>
                    <NavBar />
                    <div className={styles.page}>{children}</div>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
