name: Auto Remove Branch on Merge with Main branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to delete branches
      pull-requests: read
    steps:
      - name: Delete source branch (skip protected)
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            if (branch === "main") {
              console.log("Skip deleting 'main' branch.");
              return;
            }

            try {
              // Check if branch is protected
              await github.rest.repos.getBranchProtection({
                owner,
                repo,
                branch
              });
              console.log(`Branch '${branch}' is protected. Skipping deletion.`);
            } catch (error) {
              if (error.status === 404) {
                // No protection, safe to delete
                console.log(`Deleting branch: ${branch}`);
                await github.rest.git.deleteRef({
                  owner,
                  repo,
                  ref: `heads/${branch}`
                });
              } else {
                throw error;
              }
            }
